:development: &default
  :cities:
    :base_id: appU8z7k7vyymmPbK
    :table_name: Cities
  :employees:
    :base_id: appU8z7k7vyymmPbK
    :table_name: Employees
  :portal_modules:
    :base_id: appU8z7k7vyymmPbK
    :table_name: PortalModules
  :possibility_profiles:
    :base_id: appU8z7k7vyymmPbK
    :table_name: Results
  :quotes:
    :base_id: appU8z7k7vyymmPbK
    :table_name: Quotes
  :redirects:
    :base_id: appU8z7k7vyymmPbK
    :table_name: Redirects
  :schools:
    :base_id: appU8z7k7vyymmPbK
    :table_name: Schools
  :tasks:
    :base_id: appU8z7k7vyymmPbK
    :table_name: tasks
  :task_employees:
    :base_id: appU8z7k7vyymmPbK
    :table_name: Employees
  :commitments:
    :table_name: "Commitments"
    :shards:
      "NYC": "appU8z7k7vyymmPbK"
    #:shards:
      #"DC": "appPlrx8TnvXDshRP"
      #"DT": "app5BKrRtkoskmPHh"
      #"NHV": "appil5KLJUJgqkqWg"
      #"NYC": "appigsqPHEMnGyQh9"
      #"NWK": "appuA4jfoyAytczEp"
      #"PHL": "appf9Is4s2yLCfSp4"
      #"SF": "appntYpIBVav5pUOT"
  :students:
    :table_name: "Students"
    :shards:
      "NYC": "appU8z7k7vyymmPbK"
    #:shards:
      #"DC": "appPlrx8TnvXDshRP"
      #"DT": "app5BKrRtkoskmPHh"
      #"NHV": "appil5KLJUJgqkqWg"
      #"NYC": "appigsqPHEMnGyQh9"
      #"NWK": "appuA4jfoyAytczEp"
      #"PHL": "appf9Is4s2yLCfSp4"
      #"SF": "appntYpIBVav5pUOT"

:production:
  :cities:
    :base_id: appJi1ucZpPmznBLP
    :table_name: Cities
  :employees:
    :base_id: appJi1ucZpPmznBLP
    :table_name: Employees
  :portal_modules:
    :base_id: appJi1ucZpPmznBLP
    :table_name: PortalModules
  :possibility_profiles:
    :base_id: appYExpmKDFmpgt3j
    :table_name: Results
  :quotes:
    :base_id: appJi1ucZpPmznBLP
    :table_name: Quotes
  :redirects:
    :base_id: appJi1ucZpPmznBLP
    :table_name: Redirects
  :schools:
    :base_id: appJi1ucZpPmznBLP
    :table_name: Schools
  :task_employees:
    :base_id: appsSbGeUL5na71it
    :table_name: People
  :tasks:
    :base_id: appsSbGeUL5na71it
    :table_name: Commitments
  :commitments:
    :table_name: "Commitments"
    :shards:
      "DC": "appPlrx8TnvXDshRP"
      "DT": "app5BKrRtkoskmPHh"
      "NHV": "appil5KLJUJgqkqWg"
      "NYC": "appigsqPHEMnGyQh9"
      "NWK": "appuA4jfoyAytczEp"
      "PHL": "appf9Is4s2yLCfSp4"
      "SF": "appntYpIBVav5pUOT"
  :students:
    :table_name: "People"
    :shards:
      "DC": "appPlrx8TnvXDshRP"
      "DT": "app5BKrRtkoskmPHh"
      "NHV": "appil5KLJUJgqkqWg"
      "NYC": "appigsqPHEMnGyQh9"
      "NWK": "appuA4jfoyAytczEp"
      "PHL": "appf9Is4s2yLCfSp4"
      "SF": "appntYpIBVav5pUOT"

:test:
  <<: *default

