:development: &default
  "DC": "appPlrx8TnvXDshRP"
  "DT": "app5BKrRtkoskmPHh"
  "NHV": "appil5KLJUJgqkqWg"
  "NYC": "appigsqPHEMnGyQh9"
  "NWK": "appuA4jfoyAytczEp"
  "PHL": "appf9Is4s2yLCfSp4"
  "SF": "appntYpIBVav5pUOT"

:production:
  <<: *default

:test:
  <<: *default

