:cities:
  :bases: appU8z7k7vyymmPbK
  :table_name: Cities
:employees:
  :bases: appU8z7k7vyymmPbK
  :table_name: Employees
:portal_modules:
  :bases: appU8z7k7vyymmPbK
  :table_name: PortalModules
:possibility_profiles:
  :table_name: "Results"
  :bases: "appZtPWlnmPD8vJKP"
:quotes:
  :bases: appU8z7k7vyymmPbK
  :table_name: Quotes
:redirects:
  :bases: appU8z7k7vyymmPbK
  :table_name: Redirects
:schools:
  :bases: appU8z7k7vyymmPbK
  :table_name: Schools
:tasks:
  :bases: appU8z7k7vyymmPbK
  :table_name: tasks
:task_employees:
  :bases: appU8z7k7vyymmPbK
  :table_name: Employees
:commitments:
  :table_name: "Commitments"
  :bases:
    "NYC": "appU8z7k7vyymmPbK"
:students:
  :table_name: "People"
  :bases:
    "NYC": "appU8z7k7vyymmPbK"
#:commitments:
  #:table_name: "Commitments"
  #:bases:
    #"DC": "appPlrx8TnvXDshRP"
    #"DT": "app5BKrRtkoskmPHh"
    #"NHV": "appil5KLJUJgqkqWg"
    #"NYC": "appigsqPHEMnGyQh9"
    #"NWK": "appuA4jfoyAytczEp"
    #"PHL": "appf9Is4s2yLCfSp4"
    #"SF": "appntYpIBVav5pUOT"
