:Commitment:
  "DC": shrPU4692Gj5amf4a
  "DT": shrlQpEuTUAmFjy99
  "NHV": shrzBaT0p5hrFHMKb
  "NYC": shrMFjCiyvKz2JNpr
  "NWK": shrhVo4dBPrXKDi9s
  "PHL": shrEdKZK8IuZFn99D
  "SF": shrQaMaX5DdjmQviR
:Engagement:
  "DC": shr8uSx8An4VF69Jk
  "DT": shrDbQMIwsuheOLZn
  "NHV": shrogwTbVENo9dHxu
  "NYC": shr3zwObUhIBzxDtw
  "NWK": shr4le0szoiJIlr0T
  "PHL": shrGH1Zh7LnUgtduI
  "SF": shruq5FV15ClG2rDG
:Project:
  "DC": shr6MNL3bJmrN7Uzh
  "DT": shrEMuzP77V5BXE56
  "NHV": shr5k4plWqzJ0YB0k
  "NYC": shrRbqxM4gNXDWQfo
  "NWK": shrUbUrwiO9aUIsVO
  "PHL": shr3eWw1zdx1OmvGT
  "SF": shr2FhonVZRYAhGud
