:Commitment:
  "DC": shrlAELYrYeijZZv1
  "DT": shrlAELYrYeijZZv1
  "NHV": shrlAELYrYeijZZv1
  "NYC": shrlAELYrYeijZZv1
  "NWK": shrlAELYrYeijZZv1
  "PHL": shrlAELYrYeijZZv1
  "SF": shrlAELYrYeijZZv1
:Engagement:
  "DC": shr3UIULdzykLiiGC
  "DT": shr3UIULdzykLiiGC
  "NHV": shr3UIULdzykLiiGC
  "NYC": shr3UIULdzykLiiGC
  "NWK": shr3UIULdzykLiiGC
  "PHL": shr3UIULdzykLiiGC
  "SF": shr3UIULdzykLiiGC
:Project:
  "DC": shrtwEMSkUHus33bC
  "DT": shrtwEMSkUHus33bC
  "NHV": shrtwEMSkUHus33bC
  "NYC": shrtwEMSkUHus33bC
  "NWK": shrtwEMSkUHus33bC
  "PHL": shrtwEMSkUHus33bC
  "SF": shrtwEMSkUHus33bC
