:cities:
  :bases: appJi1ucZpPmznBLP
  :table_name: Cities
:employees:
  :bases: appJi1ucZpPmznBLP
  :table_name: Employees
:portal_modules:
  :bases: appJi1ucZpPmznBLP
  :table_name: PortalModules
:possibility_profiles:
  :table_name: Results
  :bases: app8PZoqiK1HF4xAD
:quotes:
  :bases: appJi1ucZpPmznBLP
  :table_name: Quotes
:redirects:
  :bases: appJi1ucZpPmznBLP
  :table_name: Redirects
:schools:
  :bases: appJi1ucZpPmznBLP
  :table_name: Schools
:task_employees:
  :bases: appsSbGeUL5na71it
  :table_name: People
:tasks:
  :bases: appsSbGeUL5na71it
  :table_name: Commitments
:commitments:
  :table_name: "Commitments"
  :bases:
    "DC": "appPlrx8TnvXDshRP"
    "DT": "app5BKrRtkoskmPHh"
    "NHV": "appil5KLJUJgqkqWg"
    "NYC": "appigsqPHEMnGyQh9"
    "NWK": "appuA4jfoyAytczEp"
    "PHL": "appf9Is4s2yLCfSp4"
    "SF": "appntYpIBVav5pUOT"
:students:
  :table_name: "People"
  :bases:
    "DC": "appPlrx8TnvXDshRP"
    "DT": "app5BKrRtkoskmPHh"
    "NHV": "appil5KLJUJgqkqWg"
    "NYC": "appigsqPHEMnGyQh9"
    "NWK": "appuA4jfoyAytczEp"
    "PHL": "appf9Is4s2yLCfSp4"
    "SF": "appntYpIBVav5pUOT"
